### PR TITLE
Some minor improvements

### PR DESCRIPTION
**Pull request by mast3rz3ro**

### CODE REVIEW

**Comment by kallewoof** [comment]
Thanks, again! :)

**Comment by mast3rz3ro** [comment]
My pleasure, also thanks for your great tool.

Btw, have you though on switching into LGPL licence ?

**Comment by kallewoof** [comment]
I haven't, no. Why?

**Comment by mast3rz3ro** [comment]
LGPL ensures the freedom, and forces to make sure the author is credited. While MIT notes to let the author credited however since it's a very powerful license that's will no prevent me from copying the code and releasing it back as closed source.

**Comment by kallewoof** [comment]
Considering the code is very tiny I think it's fine for people to use it in closed source.

**Comment by mast3rz3ro** [comment]
Maybe it's a tiny code but it's a very good parser.

Well than, you could be right MIT license could be enough at least for now.

Thanks you for all your efforts!

**Pull request merged**
